export const breakpoints = [
    300, 900, 1500, 2100, 2150, 2200, 2250, 2550, 2850, 3150, 3450, 3500,
    3550, 3600, 3650, 3950, 4250, 4550, 4850, 5150, 5450, 5500, 5550, 5600,
    5650,
  ];

  
  // export const variants = [
  //   'Variant B-2',
  //   'Variant A-1',
  //   'Variant A-2',
  //   'Variant A-3',
  //   'Variant A-4',
  //   'Variant B-1',
  //   'Variant B-3',
  //   'Variant B-4',
  //   'Variant B-5',
  //   'Variant B-6',
  //   'Variant B-7',
  //   'Variant B-8',
  //   'Variant C-1',
  //   'Variant C-2',
  //   'Variant C-3',
  //   'Variant C-4',
  //   'Variant C-5',
  //   'Variant C-6',
  //   'Variant D-1',
  //   'Variant D-2',
  //   'Variant D-3',
  //   'Variant D-4',
  //   'Variant E-1',
  //   'Variant E-2',
  //   'Variant E-3',
  //   'Variant E-4',
  //   'Variant E-5',
  //   'Variant E-6',
  //   'Variant E-7',
  //   'Variant F-1',
  //   'Variant F-2',
  //   'Variant F-3',
  //   'Variant F-4',
  //   'Variant F-5'
  // ];

  export const variants = [
    'Variant B-2',
    'Variant A-1',
    'Variant A-2',
    'Variant A-3',
    'Variant A-4',
    'Variant B-8',
    'Variant B-5',
    'Variant B-4',
    'Variant B-3',
    'Variant B-6',
    'Variant B-7',
    'Variant B-8',
    'Variant C-1',
    'Variant C-2',
    'Variant C-3',
    'Variant C-4',
    'Variant C-5',
    'Variant C-6',
    'Variant D-1',
    'Variant D-2',
    'Variant D-3',
    'Variant D-4',
    'Variant E-1',
    'Variant E-2',
    'Variant E-3',
    'Variant E-4',
    'Variant E-5',
    'Variant E-6',
    'Variant E-7',
    'Variant F-1',
    'Variant F-2',
    'Variant F-3',
    'Variant F-4',
    'Variant F-5'
  ]